version: '3'

tasks:
  default:
    desc: "The default task"
    dir: q
    cmds:
      - go run . exp-1
  oss-case-0:
    desc: "2 个 ECI 之间的内网通信"
    dir: q
    cmds:
      - go run . oss-case-0
  oss-case-1:
    desc: "ECI 上传到 OSS"
    dir: q
    cmds:
      - go run . oss-case-1
  oss-case-2:
    desc: "4 个 ECI 基于 OSS 进行共识"
    dir: q
    cmds:
      - go run . oss-case-2
  q:
    desc: "Run the q command help"
    dir: q
    cmds:
      - go run . --help
  proto:
    desc: "Generate the proto files"
    cmds:
      - docker compose exec -T q-dev /workspace/q/script/proto.sh